"""estrutura inicial do SmartCondo

Revision ID: 1b78d2d4fa40
Revises: 
Create Date: 2026-09-18 17:49:47.121476
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b78d2d4fa40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('logradouro', sa.String(length=180), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('sindico_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condominios_cnpj'), 'condominios', ['cnpj'], unique=True)
    op.create_index(op.f('ix_condominios_sindico_id'), 'condominios', ['sindico_id'], unique=False)
    op.create_table('espacos_comuns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('reservavel', sa.Boolean(), nullable=False),
    sa.Column('uso_livre', sa.Boolean(), nullable=False),
    sa.Column('em_manutencao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_espacos_comuns_condominio_id'), 'espacos_comuns', ['condominio_id'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('bloco', sa.String(length=20), nullable=False),
    sa.Column('andar', sa.Integer(), nullable=True),
    sa.Column('vagas_garagem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominio_id', 'bloco', 'numero', name='uq_unidade_no_condominio')
    )
    op.create_index(op.f('ix_unidades_condominio_id'), 'unidades', ['condominio_id'], unique=False)
    op.create_table('cobrancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=180), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'PAGA', 'VENCIDA', 'CANCELADA', name='status_cobranca'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_cobranca_valor_positivo'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'competencia', name='uq_cobranca_competencia')
    )
    op.create_index(op.f('ix_cobrancas_competencia'), 'cobrancas', ['competencia'], unique=False)
    op.create_index(op.f('ix_cobrancas_status'), 'cobrancas', ['status'], unique=False)
    op.create_index(op.f('ix_cobrancas_unidade_id'), 'cobrancas', ['unidade_id'], unique=False)
    op.create_index(op.f('ix_cobrancas_vencimento'), 'cobrancas', ['vencimento'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('senha_hash', sa.String(length=120), nullable=False),
    sa.Column('papel', sa.Enum('SINDICO', 'PORTEIRO', 'MORADOR', name='papel_usuario'), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_CODIGO', 'AGUARDANDO_APROVACAO', 'ATIVO', 'RECUSADO', 'INATIVO', name='status_usuario'), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ocupacao', sa.Enum('PROPRIETARIO', 'INQUILINO', 'COABITANTE', name='tipo_ocupacao'), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_condominio_id'), 'usuarios', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_unidade_id'), 'usuarios', ['unidade_id'], unique=False)
    op.create_table('codigos_verificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('finalidade', sa.Enum('CONFIRMACAO_CADASTRO', 'RECUPERACAO_SENHA', name='finalidade_codigo'), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'SMS', name='canal_verificacao'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('destino', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_verificacao_usuario_id'), 'codigos_verificacao', ['usuario_id'], unique=False)
    op.create_table('comunicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Enum('GERAL', 'MANUTENCAO', 'FINANCEIRO', 'SEGURANCA', 'EVENTO', 'URGENTE', name='categoria_comunicado'), nullable=False),
    sa.Column('fixado', sa.Boolean(), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunicados_autor_id'), 'comunicados', ['autor_id'], unique=False)
    op.create_index(op.f('ix_comunicados_categoria'), 'comunicados', ['categoria'], unique=False)
    op.create_index(op.f('ix_comunicados_condominio_id'), 'comunicados', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_comunicados_publicado_em'), 'comunicados', ['publicado_em'], unique=False)
    op.create_table('encomendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('registrada_por_id', sa.Integer(), nullable=True),
    sa.Column('remetente', sa.String(length=120), nullable=False),
    sa.Column('tipo_volume', sa.String(length=60), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=60), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO_RETIRADA', 'RETIRADA', 'RECUSADA', name='status_encomenda'), nullable=False),
    sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retirada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retirada_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retirada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encomendas_codigo_rastreio'), 'encomendas', ['codigo_rastreio'], unique=False)
    op.create_index(op.f('ix_encomendas_registrada_por_id'), 'encomendas', ['registrada_por_id'], unique=False)
    op.create_index(op.f('ix_encomendas_status'), 'encomendas', ['status'], unique=False)
    op.create_index(op.f('ix_encomendas_unidade_id'), 'encomendas', ['unidade_id'], unique=False)
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('aberta_por_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANALISE', 'RESOLVIDA', 'ARQUIVADA', name='status_ocorrencia'), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('respondida_por_id', sa.Integer(), nullable=True),
    sa.Column('respondida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aberta_por_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondida_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocorrencias_aberta_por_id'), 'ocorrencias', ['aberta_por_id'], unique=False)
    op.create_index(op.f('ix_ocorrencias_condominio_id'), 'ocorrencias', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_ocorrencias_status'), 'ocorrencias', ['status'], unique=False)
    op.create_index(op.f('ix_ocorrencias_unidade_id'), 'ocorrencias', ['unidade_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobranca_id', sa.Integer(), nullable=False),
    sa.Column('pago_por_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma', sa.Enum('PIX', 'BOLETO', 'DEBITO_AUTOMATICO', 'CARTAO', name='forma_pagamento'), nullable=False),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_pagamento_valor_positivo'),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobrancas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pago_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_cobranca_id'), 'pagamentos', ['cobranca_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_pago_por_id'), 'pagamentos', ['pago_por_id'], unique=False)
    op.create_table('permissoes_porteiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porteiro_id', sa.Integer(), nullable=False),
    sa.Column('registrar_visitantes', sa.Boolean(), nullable=False),
    sa.Column('registrar_encomendas', sa.Boolean(), nullable=False),
    sa.Column('registrar_veiculos', sa.Boolean(), nullable=False),
    sa.Column('registrar_ocorrencias', sa.Boolean(), nullable=False),
    sa.Column('acessar_financeiro', sa.Boolean(), nullable=False),
    sa.Column('definidas_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definidas_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['porteiro_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissoes_porteiro_porteiro_id'), 'permissoes_porteiro', ['porteiro_id'], unique=True)
    op.create_table('preferencias_cobranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('forma_preferida', sa.Enum('PIX', 'BOLETO', 'DEBITO_AUTOMATICO', 'CARTAO', name='forma_pagamento'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dia_vencimento BETWEEN 1 AND 28', name='ck_dia_vencimento'),
    sa.ForeignKeyConstraint(['morador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_cobranca_morador_id'), 'preferencias_cobranca', ['morador_id'], unique=True)
    op.create_table('registros_ocupacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espaco_id', sa.Integer(), nullable=False),
    sa.Column('pessoas', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pessoas >= 0', name='ck_ocupacao_nao_negativa'),
    sa.ForeignKeyConstraint(['espaco_id'], ['espacos_comuns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_ocupacao_espaco_id'), 'registros_ocupacao', ['espaco_id'], unique=False)
    op.create_index(op.f('ix_registros_ocupacao_registrado_em'), 'registros_ocupacao', ['registrado_em'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espaco_id', sa.Integer(), nullable=False),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('pessoas_estimadas', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'RECUSADA', 'CANCELADA', 'CONCLUIDA', name='status_reserva'), nullable=False),
    sa.Column('avaliada_por_id', sa.Integer(), nullable=True),
    sa.Column('avaliada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_recusa', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hora_fim > hora_inicio', name='ck_reserva_intervalo'),
    sa.ForeignKeyConstraint(['avaliada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['espaco_id'], ['espacos_comuns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['morador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_data'), 'reservas', ['data'], unique=False)
    op.create_index(op.f('ix_reservas_espaco_id'), 'reservas', ['espaco_id'], unique=False)
    op.create_index(op.f('ix_reservas_morador_id'), 'reservas', ['morador_id'], unique=False)
    op.create_index(op.f('ix_reservas_status'), 'reservas', ['status'], unique=False)
    op.create_table('visitantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('tipo_visita', sa.String(length=60), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO_CONFIRMACAO', 'CONFIRMADO', 'RECUSADO', 'DENTRO', 'SAIU', name='status_visitante'), nullable=False),
    sa.Column('entrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmado_por_id', sa.Integer(), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitantes_registrado_por_id'), 'visitantes', ['registrado_por_id'], unique=False)
    op.create_index(op.f('ix_visitantes_status'), 'visitantes', ['status'], unique=False)
    op.create_index(op.f('ix_visitantes_unidade_id'), 'visitantes', ['unidade_id'], unique=False)
    op.create_table('leituras_comunicado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comunicado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lido_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comunicado_id', 'usuario_id', name='uq_leitura_por_usuario')
    )
    op.create_index(op.f('ix_leituras_comunicado_comunicado_id'), 'leituras_comunicado', ['comunicado_id'], unique=False)
    op.create_index(op.f('ix_leituras_comunicado_usuario_id'), 'leituras_comunicado', ['usuario_id'], unique=False)
    # ### end Alembic commands ###

    # condominios.sindico_id e usuarios.condominio_id referenciam um ao
    # outro. A FK so pode ser criada depois que as duas tabelas existem.
    op.create_foreign_key(
        'fk_condominios_sindico_id', 'condominios', 'usuarios',
        ['sindico_id'], ['id'], ondelete='SET NULL',
    )


def downgrade() -> None:
    # Derruba primeiro a FK circular, senao as tabelas nao podem cair.
    op.drop_constraint('fk_condominios_sindico_id', 'condominios', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leituras_comunicado_usuario_id'), table_name='leituras_comunicado')
    op.drop_index(op.f('ix_leituras_comunicado_comunicado_id'), table_name='leituras_comunicado')
    op.drop_table('leituras_comunicado')
    op.drop_index(op.f('ix_visitantes_unidade_id'), table_name='visitantes')
    op.drop_index(op.f('ix_visitantes_status'), table_name='visitantes')
    op.drop_index(op.f('ix_visitantes_registrado_por_id'), table_name='visitantes')
    op.drop_table('visitantes')
    op.drop_index(op.f('ix_reservas_status'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_morador_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_espaco_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_data'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_registros_ocupacao_registrado_em'), table_name='registros_ocupacao')
    op.drop_index(op.f('ix_registros_ocupacao_espaco_id'), table_name='registros_ocupacao')
    op.drop_table('registros_ocupacao')
    op.drop_index(op.f('ix_preferencias_cobranca_morador_id'), table_name='preferencias_cobranca')
    op.drop_table('preferencias_cobranca')
    op.drop_index(op.f('ix_permissoes_porteiro_porteiro_id'), table_name='permissoes_porteiro')
    op.drop_table('permissoes_porteiro')
    op.drop_index(op.f('ix_pagamentos_pago_por_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_cobranca_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_ocorrencias_unidade_id'), table_name='ocorrencias')
    op.drop_index(op.f('ix_ocorrencias_status'), table_name='ocorrencias')
    op.drop_index(op.f('ix_ocorrencias_condominio_id'), table_name='ocorrencias')
    op.drop_index(op.f('ix_ocorrencias_aberta_por_id'), table_name='ocorrencias')
    op.drop_table('ocorrencias')
    op.drop_index(op.f('ix_encomendas_unidade_id'), table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_status'), table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_registrada_por_id'), table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_codigo_rastreio'), table_name='encomendas')
    op.drop_table('encomendas')
    op.drop_index(op.f('ix_comunicados_publicado_em'), table_name='comunicados')
    op.drop_index(op.f('ix_comunicados_condominio_id'), table_name='comunicados')
    op.drop_index(op.f('ix_comunicados_categoria'), table_name='comunicados')
    op.drop_index(op.f('ix_comunicados_autor_id'), table_name='comunicados')
    op.drop_table('comunicados')
    op.drop_index(op.f('ix_codigos_verificacao_usuario_id'), table_name='codigos_verificacao')
    op.drop_table('codigos_verificacao')
    op.drop_index(op.f('ix_usuarios_unidade_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_condominio_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cobrancas_vencimento'), table_name='cobrancas')
    op.drop_index(op.f('ix_cobrancas_unidade_id'), table_name='cobrancas')
    op.drop_index(op.f('ix_cobrancas_status'), table_name='cobrancas')
    op.drop_index(op.f('ix_cobrancas_competencia'), table_name='cobrancas')
    op.drop_table('cobrancas')
    op.drop_index(op.f('ix_unidades_condominio_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_espacos_comuns_condominio_id'), table_name='espacos_comuns')
    op.drop_table('espacos_comuns')
    op.drop_index(op.f('ix_condominios_sindico_id'), table_name='condominios')
    op.drop_index(op.f('ix_condominios_cnpj'), table_name='condominios')
    op.drop_table('condominios')
    # ### end Alembic commands ###

    # O drop_table do PostgreSQL nao remove os tipos ENUM criados junto
    # com as colunas; sem isto, um novo upgrade falha com "type already exists".
    for tipo in (
        'canal_verificacao',
        'categoria_comunicado',
        'finalidade_codigo',
        'forma_pagamento',
        'papel_usuario',
        'status_cobranca',
        'status_encomenda',
        'status_ocorrencia',
        'status_reserva',
        'status_usuario',
        'status_visitante',
        'tipo_ocupacao',
    ):
        op.execute(f'DROP TYPE IF EXISTS {tipo}')
