"""veiculos ordens de servico e documentos

Revision ID: 890a8059b8a1
Revises: a36d1fb5ea68
Create Date: 2026-09-21 01:39:19.003016
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '890a8059b8a1'
down_revision: Union[str, None] = 'a36d1fb5ea68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('CONVENCAO', 'REGIMENTO', 'ATA', 'PLANTA', 'PRESTACAO_CONTAS', 'OUTRO', name='categoria_documento'), nullable=False),
    sa.Column('arquivo_url', sa.String(length=500), nullable=False),
    sa.Column('tamanho_kb', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('publicado_por_id', sa.Integer(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publicado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_categoria'), 'documentos', ['categoria'], unique=False)
    op.create_index(op.f('ix_documentos_condominio_id'), 'documentos', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_documentos_publicado_em'), 'documentos', ['publicado_em'], unique=False)
    op.create_index(op.f('ix_documentos_publicado_por_id'), 'documentos', ['publicado_por_id'], unique=False)
    op.create_index(op.f('ix_documentos_unidade_id'), 'documentos', ['unidade_id'], unique=False)
    op.create_table('movimentacoes_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipo_movimentacao'), nullable=False),
    sa.Column('categoria', sa.Enum('MORADOR', 'VISITANTE', 'PRESTADOR', name='categoria_veiculo'), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('registrada_por_id', sa.Integer(), nullable=True),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_veiculo_condominio_id'), 'movimentacoes_veiculo', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_veiculo_placa'), 'movimentacoes_veiculo', ['placa'], unique=False)
    op.create_index(op.f('ix_movimentacoes_veiculo_registrada_em'), 'movimentacoes_veiculo', ['registrada_em'], unique=False)
    op.create_index(op.f('ix_movimentacoes_veiculo_registrada_por_id'), 'movimentacoes_veiculo', ['registrada_por_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_veiculo_tipo'), 'movimentacoes_veiculo', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_veiculo_unidade_id'), 'movimentacoes_veiculo', ['unidade_id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridade_ordem_servico'), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='status_ordem_servico'), nullable=False),
    sa.Column('fornecedor', sa.String(length=120), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('custo_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aberta_por_id', sa.Integer(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('custo_estimado IS NULL OR custo_estimado >= 0', name='ck_os_custo_estimado'),
    sa.CheckConstraint('custo_real IS NULL OR custo_real >= 0', name='ck_os_custo_real'),
    sa.ForeignKeyConstraint(['aberta_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_aberta_por_id'), 'ordens_servico', ['aberta_por_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_condominio_id'), 'ordens_servico', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_prioridade'), 'ordens_servico', ['prioridade'], unique=False)
    op.create_index(op.f('ix_ordens_servico_status'), 'ordens_servico', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordens_servico_status'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_prioridade'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_condominio_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_aberta_por_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_movimentacoes_veiculo_unidade_id'), table_name='movimentacoes_veiculo')
    op.drop_index(op.f('ix_movimentacoes_veiculo_tipo'), table_name='movimentacoes_veiculo')
    op.drop_index(op.f('ix_movimentacoes_veiculo_registrada_por_id'), table_name='movimentacoes_veiculo')
    op.drop_index(op.f('ix_movimentacoes_veiculo_registrada_em'), table_name='movimentacoes_veiculo')
    op.drop_index(op.f('ix_movimentacoes_veiculo_placa'), table_name='movimentacoes_veiculo')
    op.drop_index(op.f('ix_movimentacoes_veiculo_condominio_id'), table_name='movimentacoes_veiculo')
    op.drop_table('movimentacoes_veiculo')
    op.drop_index(op.f('ix_documentos_unidade_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_publicado_por_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_publicado_em'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_condominio_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_categoria'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###

    # O drop_table do PostgreSQL nao remove os tipos ENUM criados junto com
    # as colunas; sem isto, um novo upgrade falha com "type already exists".
    for tipo in (
        'categoria_documento',
        'categoria_veiculo',
        'prioridade_ordem_servico',
        'status_ordem_servico',
        'tipo_movimentacao',
    ):
        op.execute(f'DROP TYPE IF EXISTS {tipo}')
