"""codigo de acesso do condominio

Revision ID: a684b94fc284
Revises: 1b78d2d4fa40
Create Date: 2026-09-18 18:34:45.874007
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.security import gerar_codigo_condominio


revision: str = 'a684b94fc284'
down_revision: Union[str, None] = '1b78d2d4fa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A coluna é obrigatória, mas as linhas que já existem não têm valor.
    # Entra como nula, recebe um código gerado e só então vira NOT NULL.
    op.add_column('condominios', sa.Column('codigo_acesso', sa.String(length=20), nullable=True))

    conexao = op.get_bind()
    linhas = conexao.execute(sa.text('SELECT id, nome FROM condominios')).fetchall()
    usados = set()
    for id_condominio, nome in linhas:
        codigo = gerar_codigo_condominio(nome or '')
        while codigo in usados:
            codigo = gerar_codigo_condominio(nome or '')
        usados.add(codigo)
        conexao.execute(
            sa.text('UPDATE condominios SET codigo_acesso = :codigo WHERE id = :id'),
            {'codigo': codigo, 'id': id_condominio},
        )

    op.alter_column('condominios', 'codigo_acesso', nullable=False)
    op.create_index(op.f('ix_condominios_codigo_acesso'), 'condominios', ['codigo_acesso'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condominios_codigo_acesso'), table_name='condominios')
    op.drop_column('condominios', 'codigo_acesso')
    # ### end Alembic commands ###
